# Generated by Django 2.1.1 on 2018-09-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(verbose_name='Resposta')),
                ('iscorrect', models.BooleanField(default=False, verbose_name='É correta?')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
                ('imagem', models.FileField(upload_to='', verbose_name='Imagem')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Questão')),
                ('level', models.IntegerField(choices=[(1, 'Easy'), (5, 'Medium'), (9, 'Hard')], default=1, verbose_name='Nível')),
                ('question_type', models.IntegerField(choices=[(1, 'Pergunta e Resposta'), (2, 'Clicar na imagem')], default=1, verbose_name='Tipo de Questão')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Explicação')),
                ('category', models.ForeignKey(on_delete=None, to='quiz.Category', verbose_name='Category')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=None, to='base.Country', verbose_name='País')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=None, to='base.Region', verbose_name='Região')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=None, to='quiz.Question', verbose_name='Pergunta'),
        ),
    ]
