# Generated by Django 2.1.1 on 2018-09-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180923_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
