# Generated by Django 2.1.1 on 2018-09-23 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_auto_20180923_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correta', models.BooleanField(default=False, verbose_name='Está correta?')),
                ('answer', models.ForeignKey(on_delete=None, to='quiz.Answer', verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'resposta do usuário',
                'verbose_name_plural': 'respostas dos usuários',
                'db_table': 'useranswer',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=None, to='quiz.Category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=None, to='quiz.Question', verbose_name='Pergunta'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='usuario',
            field=models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
