# Generated by Django 2.1.1 on 2018-09-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='user_permissions',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'país', 'verbose_name_plural': 'países'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'região', 'verbose_name_plural': 'regiões'},
        ),
        migrations.DeleteModel(
            name='Gamer',
        ),
    ]
